# üéØ Projeto 3: An√°lise de Desigualdade Educacional no Brasil


Esse notebook servir√° para anotar as ideias, as analises aleatorias feitas e demais coisas.

Em outro notebook ter√° a organiza√ß√£o bem feita das an√°lises


## üìå Tema:
Vamos usar dados do INEP (Ideb) ou Censo Escolar para analisar desigualdades educacionais entre diferentes regi√µes do Brasil. O foco ser√° comparar indicadores como taxa de aprova√ß√£o, evas√£o, n√∫mero de alunos por turma e IDEB em diferentes estados, anos e redes de ensino (p√∫blica x privada).

## üîó Fonte de Dados:

Para os dados, utilizei os microdados dos dados abertos do Censo Escolar 2024, que podem ser conferidas logo abaixo: 

- [Microdados do Censo Escolar](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-escolar)

## üí° Uma mudan√ßa

A base de dados do Censo Escolar √© muito extensa para eu trabalhar como um iniciante. Eu decidi trabalhar apenas com um estado inicialmente, e posteriormente ir trabalhando com os outros estados, captando pequenas mudan√ßas se necess√°rio. 

Ao observar os dados, e tamb√©m o dicion√°rio de dados, foi perceptivel que existe muita informa√ß√£o ao qual da para ser trablhada com apenas um estado, e assim conseguirei atingir meus objetivos iniciais. Outro motivo tamb√©m foi porque assim tamb√©m terei uma facilidade no entendimento do contexto local dos estados.

Irei ent√£o trabalhar com o estado de **Pernambuco**

In [1]:
import pandas as pd

In [20]:
# O arquivo que antes estava nesse local foi apagado, pois pesava muito
# df = pd.read_csv("microdados_censo_escolar_2024/dados/microdados_ed_basica_2024.csv", sep=';', encoding='latin1')
# df_estado = df[df['SG_UF'] == 'PE']

In [21]:
# Salvando o DataFrame s√≥ com as informa√ß√µes do estado de 'Pernambuco'
# df_estado.to_csv('microdados_censo_PE_2024.csv', index=False)

In [2]:
# Abaixo est√° o arquivo csv salvo ap√≥s filtrar apenas para um √∫nico estado
df = pd.read_csv("microdados_censo_escolar_2024/dados/microdados_censo_PE_2024.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9936 entries, 0 to 9935
Columns: 426 entries, NU_ANO_CENSO to QT_TUR_MED_INT
dtypes: float64(396), int64(14), object(16)
memory usage: 32.3+ MB

In [17]:
df.columns

Index(['NU_ANO_CENSO', 'NO_REGIAO', 'CO_REGIAO', 'NO_UF', 'SG_UF', 'CO_UF',
       'NO_MUNICIPIO', 'CO_MUNICIPIO', 'NO_REGIAO_GEOG_INTERM',
       'CO_REGIAO_GEOG_INTERM',
       ...
       'QT_TUR_BAS_D', 'QT_TUR_BAS_N', 'QT_TUR_BAS_EAD', 'QT_TUR_INF_INT',
       'QT_TUR_INF_CRE_INT', 'QT_TUR_INF_PRE_INT', 'QT_TUR_FUND_INT',
       'QT_TUR_FUND_AI_INT', 'QT_TUR_FUND_AF_INT', 'QT_TUR_MED_INT'],
      dtype='object', length=426)

In [16]:
df.isnull().sum()

NU_ANO_CENSO             0
NO_REGIAO                0
CO_REGIAO                0
NO_UF                    0
SG_UF                    0
                      ...
QT_TUR_INF_PRE_INT    1943
QT_TUR_FUND_INT       1943
QT_TUR_FUND_AI_INT    1943
QT_TUR_FUND_AF_INT    1943
QT_TUR_MED_INT        1943
Length: 426, dtype: int64

In [18]:
df.head()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
0,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,18.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,12.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,15.0,9.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0
4,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.tail()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
9931,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9932,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9933,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9934,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,11.0,4.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0
9935,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

___

**Importante**

Ao observar o dicion√°rio de dados (`est√° em Anexo I`), foi visto que n√£o tem uma maneira de reduzir a quantidade de colunas do dataframe, que se encontram em 426. 

Com isso em mente, irei tentar trabalhar da melhor maneira possivel para obter uma an√°lise de boa qualidade para esse meu pequeno projeto. Irei sempre estar utilizando o dicion√°rio de dados para conseguir identificar o que determinada coluna me informa, ou at√© mesmo para encontrar mais facilmente algum informa√ß√£o de coluna para utilizar.

In [3]:
# Todas as colunas do dataframe
#df.columns.tolist()

___

# Algumas Ideias...

## üóÇÔ∏è Algumas perguntas que est√£o surgindo para a an√°lise:

- Qual a taxa de aprova√ß√£o m√©dia por munic√≠pio?
- A infraestrutura das escolas (biblioteca, laborat√≥rio, internet) influencia nos resultados?
- Quantas escolas por tipo de rede (p√∫blica, privada)?
- Qual o perfil dos docentes?

Vou separar por categorias, acredito que fica melhor.


üéØ Perfil das Escolas

- Qual a quantidade total de escolas por rede (p√∫blica x privada)?
- Qual o percentual de escolas que possuem biblioteca, laborat√≥rio de inform√°tica, quadra esportiva ou acesso √† internet?
- Quais s√£o os munic√≠pios com maior n√∫mero de escolas?
- Qual o percentual de escolas urbanas x rurais?
- Qual a m√©dia de alunos por escola?
- Qual a distribui√ß√£o das escolas por etapas de ensino (fundamental, m√©dio, EJA, etc.)?

üéØ Perfil dos Alunos

- Quantos alunos est√£o matriculados no estado por rede de ensino?
- Qual a m√©dia de alunos por turma (ou sala)?
- Qual a propor√ß√£o de alunos na zona urbana x zona rural?
- Qual o percentual de alunos com necessidades especiais atendidos nas escolas?
- Quantos alunos por munic√≠pio? Existe concentra√ß√£o em alguns polos?
- Existe diferen√ßa de matr√≠cula por sexo?

üéØ Perfil dos Docentes

- Qual a quantidade total de docentes no estado?
- Qual o percentual de docentes com ensino superior completo?
- Qual a m√©dia de alunos por docente?
- Quais s√£o os munic√≠piods com mais professores?
- Existem diferen√ßas na forma√ß√£o dos docentes entre escolas p√∫blicas e privadas?

üéØ Infraestrutura Escolar x Indicadores

b- Existe rela√ß√£o entre a presen√ßa de laborat√≥rio de inform√°tica e o n√∫mero m√©dio de alunos?
- Qual a infraestrutura mais presente nas escolas p√∫blicas? E nas privadas?
- Infraestrutura varia muito entre zonas urbana e rural?

üéØ Comparativos

- Qual a diferen√ßa de estrutura e n√∫mero de alunos entre escolas urbanas e rurais?
- Qual a diferen√ßa entre as redes p√∫blica e privada?
- Como est√° a distribui√ß√£o das escolas por munic√≠pio em rela√ß√£o √† popula√ß√£o (ex: escolas per capita)?

üéØ Poss√≠veis Cruzes de Dados (Para aprofundar)
- Munic√≠pios com mais escolas p√∫blicas possuem tamb√©m maior n√∫mero de docentes qualificados?
- Escolas p√∫blicas em √°reas urbanas t√™m infraestrutura melhor que em √°reas rurais?
- Escolas que oferecem mais etapas de ensino concentram mais alunos?

üéØ An√°lises Temporais (Se tiver mais anos)
- O n√∫mero de matr√≠culas cresceu ou diminuiu ao longo dos anos?
- Como a pandemia afetou as matr√≠culas ou n√∫mero de docentes?
- A infraestrutura das escolas melhorou nos √∫ltimos anos?

## üóÇÔ∏è Sugest√µes de An√°lises para o Projeto

### 1Ô∏è‚É£ Panorama das Escolas no Estado

- Quantas escolas existem no estado por rede de ensino (p√∫blica/privada)?
- Quantas escolas t√™m biblioteca, laborat√≥rio, internet?
- Distribui√ß√£o do n√∫mero de alunos por escola.

Insight esperado: ‚ÄúNo estado de SP, apenas 40% das escolas p√∫blicas possuem laborat√≥rio de inform√°tica.‚Äù

### 2Ô∏è‚É£ Infraestrutura x Rede de Ensino

- Qual a diferen√ßa de infraestrutura entre escolas p√∫blicas e privadas?
- Existe diferen√ßa significativa no acesso √† internet, quadra, biblioteca?
- Gr√°ficos sugeridos:
    - Barras comparativas
    - Heatmap de correla√ß√£o por rede

### 3Ô∏è‚É£ N√∫mero de Alunos por Munic√≠pio

- Quais s√£o os 10 munic√≠pios com maior n√∫mero de alunos matriculados?
- Existe rela√ß√£o entre o tamanho do munic√≠pio (n√∫mero de escolas) e o n√∫mero m√©dio de alunos por escola?

Poss√≠vel insight: ‚ÄúMunic√≠pios menores t√™m turmas mais cheias em escolas p√∫blicas.‚Äù

### 4Ô∏è‚É£ Docentes e Qualifica√ß√£o

- Qual a propor√ß√£o de docentes com forma√ß√£o superior por rede?
- H√° diferen√ßa na forma√ß√£o de professores da rede p√∫blica e privada?
- Gr√°fico sugerido: Barras empilhadas ou porcentagem

### 5Ô∏è‚É£ An√°lise Temporal (se tiver mais de um ano)

- Como evoluiu o n√∫mero de matr√≠culas nos √∫ltimos anos?
- Houve queda de matr√≠cula na pandemia?

### 6Ô∏è‚É£ Geolocaliza√ß√£o (Extra)

- Se quiser ousar, pode mapear as escolas no estado usando as coordenadas (se vierem na base).
- Ou plotar por munic√≠pio.

In [5]:
# Analise ale√°toria
colunas_desejadas = ['NO_MUNICIPIO', 'NO_ENTIDADE', 'IN_AGUA_POTAVEL', 'IN_AGUA_REDE_PUBLICA', 'IN_AGUA_POCO_ARTESIANO', 'IN_AGUA_CACIMBA', 'IN_AGUA_FONTE_RIO', 'IN_AGUA_INEXISTENTE', 'IN_AGUA_CARRO_PIPA']


# Visualizar as colunas sobre a agua das escolas
df_copia1 = df[colunas_desejadas]

In [6]:
df_copia1[df_copia1['NO_MUNICIPIO'] == 'Itamb√©'].head()

,NO_MUNICIPIO,NO_ENTIDADE,IN_AGUA_POTAVEL,IN_AGUA_REDE_PUBLICA,IN_AGUA_POCO_ARTESIANO,IN_AGUA_CACIMBA,IN_AGUA_FONTE_RIO,IN_AGUA_INEXISTENTE,IN_AGUA_CARRO_PIPA
3819,Itamb√©,ESCOLA DE REFERENCIA EM ENSINO MEDIO FREI ORLANDO,1.0,1.0,0.0,0.0,0.0,0.0,0.0
3820,Itamb√©,COLEGIO MUNICIPAL PROFESSOR NIVALDO XAVIER DE ...,1.0,1.0,0.0,1.0,0.0,0.0,0.0
3821,Itamb√©,ESCOLA ARRUDA CAMARA,1.0,1.0,0.0,1.0,0.0,0.0,0.0
3822,Itamb√©,ESCOLA MUL ALVARO VELOSO BORBA,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3823,Itamb√©,ESC MUL ANTONIO GUEDES CORREIA GONDIM,1.0,0.0,0.0,1.0,0.0,0.0,0.0

## üéØ Perfil das Escolas

- Qual a quantidade total de escolas por rede (p√∫blica x privada)?
- Qual o percentual de escolas que possuem biblioteca, laborat√≥rio de inform√°tica, quadra esportiva ou acesso √† internet?
- Quais s√£o os munic√≠pios com maior n√∫mero de escolas?
- Qual o percentual de escolas urbanas x rurais?
- Qual a m√©dia de alunos por escola?
- Qual a distribui√ß√£o das escolas por etapas de ensino (fundamental, m√©dio, EJA, etc.)?

In [9]:
# Quantas escolas est√£o em situa√ß√£o de n√£o funcionamento?
df['TP_SITUACAO_FUNCIONAMENTO'].value_counts()

TP_SITUACAO_FUNCIONAMENTO
1    8013
2    1809
3     114
Name: count, dtype: int64

- Existem 8013 escolas **Em atividade** no estado de Pernambuco;
- Ao momento s√£o 1809 escolas **paralisadas**; e
- 114 escolas foram **extintas** desde o √∫ltimo censo.

In [13]:
colunas_desejadas_vinculo = ['NO_MUNICIPIO', 'NO_ENTIDADE', 
                             'IN_VINCULO_SECRETARIA_EDUCACAO', 'IN_VINCULO_SEGURANCA_PUBLICA', 'IN_VINCULO_SECRETARIA_SAUDE', 
                             'IN_VINCULO_OUTRO_ORGAO', 'IN_PODER_PUBLICO_PARCERIA', 'TP_PODER_PUBLICO_PARCERIA']

df_vinculo = df[colunas_desejadas_vinculo]

In [16]:
df_vinculo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9936 entries, 0 to 9935
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NO_MUNICIPIO                    9936 non-null   object
 1   NO_ENTIDADE                     9936 non-null   object
 2   IN_VINCULO_SECRETARIA_EDUCACAO  5842 non-null   float64
 3   IN_VINCULO_SEGURANCA_PUBLICA    5842 non-null   float64
 4   IN_VINCULO_SECRETARIA_SAUDE     5842 non-null   float64
 5   IN_VINCULO_OUTRO_ORGAO          5842 non-null   float64
 6   IN_PODER_PUBLICO_PARCERIA       8013 non-null   float64
 7   TP_PODER_PUBLICO_PARCERIA       184 non-null    float64
dtypes: float64(6), object(2)
memory usage: 621.1+ KB

In [26]:
df['IN_VINCULO_SECRETARIA_EDUCACAO'].value_counts()

IN_VINCULO_SECRETARIA_EDUCACAO
1.0    5839
0.0       3
Name: count, dtype: int64

In [36]:
# df.groupby('IN_PROF_ADMINISTRATIVOS')['QT_PROF_ADMINISTRATIVOS'].sum()
# df_admin = df[df['IN_PROF_ADMINISTRATIVOS'] == 1]

df_filtro_profisionais = df[
    (df['IN_PROF_ADMINISTRATIVOS'] == 1) &
    (df['IN_PROF_SERVICOS_GERAIS'] == 1) &
    (df['IN_PROF_BIBLIOTECARIO'] == 1) &
    (df['IN_PROF_SAUDE'] == 1) &
    (df['IN_PROF_COORDENADOR'] == 1) &
    (df['IN_PROF_FONAUDIOLOGO'] == 1) &
    (df['IN_PROF_NUTRICIONISTA'] == 1) &
    (df['IN_PROF_PSICOLOGO'] == 1) &
    (df['IN_PROF_ALIMENTACAO'] == 1) &
    (df['IN_PROF_PEDAGOGIA'] == 1) &
    (df['IN_PROF_SECRETARIO'] == 1) &
    (df['IN_PROF_SEGURANCA'] == 1) &
    (df['IN_PROF_MONITORES'] == 1) &
    (df['IN_PROF_ASSIST_SOCIAL'] == 1) &
    (df['IN_PROF_TRAD_LIBRAS'] == 1)
]

In [59]:
# df.groupby('IN_PROF_ADMINISTRATIVOS')['QT_PROF_ADMINISTRATIVOS'].sum()
# df_admin = df[df['IN_PROF_ADMINISTRATIVOS'] == 1]

df_filtro_profisionais2 = df[
    (df['IN_PROF_ADMINISTRATIVOS'] == 1) |
    (df['IN_PROF_SERVICOS_GERAIS'] == 1) |
    (df['IN_PROF_BIBLIOTECARIO'] == 1) |
    (df['IN_PROF_SAUDE'] == 1) |
    (df['IN_PROF_COORDENADOR'] == 1) |
    (df['IN_PROF_FONAUDIOLOGO'] == 1) |
    (df['IN_PROF_NUTRICIONISTA'] == 1) |
    (df['IN_PROF_PSICOLOGO'] == 1) |
    (df['IN_PROF_ALIMENTACAO'] == 1) |
    (df['IN_PROF_PEDAGOGIA'] == 1) |
    (df['IN_PROF_SECRETARIO'] == 1) |
    (df['IN_PROF_SEGURANCA'] == 1) |
    (df['IN_PROF_MONITORES'] == 1) |
    (df['IN_PROF_ASSIST_SOCIAL'] == 1) |
    (df['IN_PROF_TRAD_LIBRAS'] == 1)
]

In [67]:
df[['IN_PROF_ADMINISTRATIVOS', 'IN_PROF_SERVICOS_GERAIS', 'IN_PROF_BIBLIOTECARIO']]

      IN_PROF_ADMINISTRATIVOS  IN_PROF_SERVICOS_GERAIS  IN_PROF_BIBLIOTECARIO
0                         NaN                      NaN                    NaN
1                         1.0                      1.0                    0.0
2                         1.0                      1.0                    0.0
3                         1.0                      1.0                    0.0
4                         NaN                      NaN                    NaN
...                       ...                      ...                    ...
9931                      1.0                      1.0                    0.0
9932                      NaN                      NaN                    NaN
9933                      1.0                      1.0                    0.0
9934                      1.0                      1.0                    0.0
9935                      1.0                      1.0                    0.0

[9936 rows x 3 columns]

In [56]:
df_filtro_profisionais2

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
1,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,18.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,12.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,15.0,9.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0
5,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,16.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2024,Nordeste,2,Pernambuco,PE,26,Abreu e Lima,2600054,Recife,2601,...,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9930,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9931,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9933,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9934,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,11.0,4.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0
9935,2024,Nordeste,2,Pernambuco,PE,26,Xex√©u,2616506,Recife,2601,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
df_filtro_profisionais2[['NO_MUNICIPIO', 'NO_ENTIDADE', 'IN_PROF_PSICOLOGO']]

,NO_MUNICIPIO,NO_ENTIDADE,IN_PROF_PSICOLOGO
1,Abreu e Lima,EM - CENTRO COMU E EDUC ISAAC MARTINS RODRIGUES,0.0
2,Abreu e Lima,EM - CENTRO COM EDUCACIONAL WILIBALDO DE FRANC...,0.0
3,Abreu e Lima,ESCOLA DE REFERENCIA EM ENSINO FUNDAMENTAL GEN...,0.0
5,Abreu e Lima,ESCOLA MARECHAL COSTA E SILVA,0.0
7,Abreu e Lima,EM - ESCOLA MUNICIPAL DE ENGENHO NOVO,0.0
...,...,...,...
9930,Xex√©u,ESCOLA MUNICIPAL TEREZINHA BARBOSA DA SILVA,0.0
9931,Xex√©u,ESCOLA MUNICIPAL JOAO FOGUETEIRO,1.0
9933,Xex√©u,CRECHE MUNICIPAL PROFESSORA ETIENE LINS BARRETO,1.0
9934,Xex√©u,ESCOLA MUNICIPAL PROFESSORA ISABEL DE CASSIA M...,1.0
9935,Xex√©u,ESCOLA MUNICIPAL DR JOSE HAMILTON LINS,0.0

In [69]:
df.isnull().sum().sort_values(ascending=False)

CO_LINGUA_INDIGENA_3              9936
CO_ESCOLA_SEDE_VINCULADA          9933
CO_LINGUA_INDIGENA_2              9931
IN_FORMA_CONT_ES_COOP_TEC_FIN     9926
IN_FORMA_CONT_ES_TERMO_FOMENTO    9926
                                  ...
SG_UF                                0
NO_UF                                0
CO_REGIAO                            0
NO_REGIAO                            0
NU_ANO_CENSO                         0
Length: 426, dtype: int64

In [70]:
# Ver colunas que t√™m mais de X% de valores nulos (exemplo: mais de 50%)
porcentagem_nulos = df.isnull().mean() * 100  # Em porcentagem
colunas_com_muitos_nulos = porcentagem_nulos[porcentagem_nulos > 50]
print(colunas_com_muitos_nulos)

TP_CATEGORIA_ESCOLA_PRIVADA        78.150161
DS_COMPLEMENTO                     77.425523
TP_PODER_PUBLICO_PARCERIA          98.148148
IN_FORMA_CONT_TERMO_COLABORA       98.148148
IN_FORMA_CONT_TERMO_FOMENTO        98.148148
IN_FORMA_CONT_ACORDO_COOP          98.148148
IN_FORMA_CONT_PRESTACAO_SERV       98.148148
IN_FORMA_CONT_COOP_TEC_FIN         98.148148
IN_FORMA_CONT_CONSORCIO_PUB        98.148148
IN_FORMA_CONT_MU_TERMO_COLAB       98.248792
IN_FORMA_CONT_MU_TERMO_FOMENTO     98.248792
IN_FORMA_CONT_MU_ACORDO_COOP       98.248792
IN_FORMA_CONT_MU_PREST_SERV        98.248792
IN_FORMA_CONT_MU_COOP_TEC_FIN      98.248792
IN_FORMA_CONT_MU_CONSORCIO_PUB     98.248792
IN_FORMA_CONT_ES_TERMO_COLAB       99.899356
IN_FORMA_CONT_ES_TERMO_FOMENTO     99.899356
IN_FORMA_CONT_ES_ACORDO_COOP       99.899356
IN_FORMA_CONT_ES_PREST_SERV        99.899356
IN_FORMA_CONT_ES_COOP_TEC_FIN      99.899356
IN_FORMA_CONT_ES_CONSORCIO_PUB     99.899356
IN_MANT_ESCOLA_PRIVADA_EMP         78.150161
IN_MANT_ESCOLA_PRIVADA_ONG         78.150161
IN_MANT_ESCOLA_PRIVADA_OSCIP       78.150161
IN_MANT_ESCOLA_PRIV_ONG_OSCIP      78.150161
IN_MANT_ESCOLA_PRIVADA_SIND        78.150161
IN_MANT_ESCOLA_PRIVADA_SIST_S      78.150161
IN_MANT_ESCOLA_PRIVADA_S_FINS      78.150161
NU_CNPJ_ESCOLA_PRIVADA             78.150161
NU_CNPJ_MANTENEDORA                78.150161
CO_ESCOLA_SEDE_VINCULADA           99.969807
CO_IES_OFERTANTE                   99.828905
TP_OCUPACAO_GALPAO                 99.647746
TP_INDIGENA_LINGUA                 98.379630
CO_LINGUA_INDIGENA_1               99.879227
CO_LINGUA_INDIGENA_2               99.949678
CO_LINGUA_INDIGENA_3              100.000000
IN_RESERVA_PPI                     96.769324
IN_RESERVA_RENDA                   96.769324
IN_RESERVA_PUBLICA                 96.769324
IN_RESERVA_PCD                     96.769324
IN_RESERVA_OUTROS                  96.769324
IN_RESERVA_NENHUMA                 96.769324
dtype: float64

In [72]:
df[colunas_com_muitos_nulos.index].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9936 entries, 0 to 9935
Data columns (total 43 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   TP_CATEGORIA_ESCOLA_PRIVADA     2171 non-null   float64
 1   DS_COMPLEMENTO                  2243 non-null   object
 2   TP_PODER_PUBLICO_PARCERIA       184 non-null    float64
 3   IN_FORMA_CONT_TERMO_COLABORA    184 non-null    float64
 4   IN_FORMA_CONT_TERMO_FOMENTO     184 non-null    float64
 5   IN_FORMA_CONT_ACORDO_COOP       184 non-null    float64
 6   IN_FORMA_CONT_PRESTACAO_SERV    184 non-null    float64
 7   IN_FORMA_CONT_COOP_TEC_FIN      184 non-null    float64
 8   IN_FORMA_CONT_CONSORCIO_PUB     184 non-null    float64
 9   IN_FORMA_CONT_MU_TERMO_COLAB    174 non-null    float64
 10  IN_FORMA_CONT_MU_TERMO_FOMENTO  174 non-null    float64
 11  IN_FORMA_CONT_MU_ACORDO_COOP    174 non-null    float64
 12  IN_FORMA_CONT_MU_PREST_SERV     174 non-null    float64
 13  IN_FORMA_CONT_MU_COOP_TEC_FIN   174 non-null    float64
 14  IN_FORMA_CONT_MU_CONSORCIO_PUB  174 non-null    float64
 15  IN_FORMA_CONT_ES_TERMO_COLAB    10 non-null     float64
 16  IN_FORMA_CONT_ES_TERMO_FOMENTO  10 non-null     float64
 17  IN_FORMA_CONT_ES_ACORDO_COOP    10 non-null     float64
 18  IN_FORMA_CONT_ES_PREST_SERV     10 non-null     float64
 19  IN_FORMA_CONT_ES_COOP_TEC_FIN   10 non-null     float64
 20  IN_FORMA_CONT_ES_CONSORCIO_PUB  10 non-null     float64
 21  IN_MANT_ESCOLA_PRIVADA_EMP      2171 non-null   float64
 22  IN_MANT_ESCOLA_PRIVADA_ONG      2171 non-null   float64
 23  IN_MANT_ESCOLA_PRIVADA_OSCIP    2171 non-null   float64
 24  IN_MANT_ESCOLA_PRIV_ONG_OSCIP   2171 non-null   float64
 25  IN_MANT_ESCOLA_PRIVADA_SIND     2171 non-null   float64
 26  IN_MANT_ESCOLA_PRIVADA_SIST_S   2171 non-null   float64
 27  IN_MANT_ESCOLA_PRIVADA_S_FINS   2171 non-null   float64
 28  NU_CNPJ_ESCOLA_PRIVADA          2171 non-null   float64
 29  NU_CNPJ_MANTENEDORA             2171 non-null   float64
 30  CO_ESCOLA_SEDE_VINCULADA        3 non-null      float64
 31  CO_IES_OFERTANTE                17 non-null     float64
 32  TP_OCUPACAO_GALPAO              35 non-null     float64
 33  TP_INDIGENA_LINGUA              161 non-null    float64
 34  CO_LINGUA_INDIGENA_1            12 non-null     float64
 35  CO_LINGUA_INDIGENA_2            5 non-null      float64
 36  CO_LINGUA_INDIGENA_3            0 non-null      float64
 37  IN_RESERVA_PPI                  321 non-null    float64
 38  IN_RESERVA_RENDA                321 non-null    float64
 39  IN_RESERVA_PUBLICA              321 non-null    float64
 40  IN_RESERVA_PCD                  321 non-null    float64
 41  IN_RESERVA_OUTROS               321 non-null    float64
 42  IN_RESERVA_NENHUMA              321 non-null    float64
dtypes: float64(42), object(1)
memory usage: 3.3+ MB

In [26]:
df_itambe = df[df['NO_MUNICIPIO'] == 'Itamb√©']

In [17]:
df.fillna(0)

NU_ANO_CENSO          0
NO_REGIAO             0
CO_REGIAO             0
NO_UF                 0
SG_UF                 0
                     ..
QT_TUR_INF_PRE_INT    0
QT_TUR_FUND_INT       0
QT_TUR_FUND_AI_INT    0
QT_TUR_FUND_AF_INT    0
QT_TUR_MED_INT        0
Length: 426, dtype: int64

In [19]:
# Identificando os tipos das colunas com valores nulos:
colunas_nulas = df.columns[df.isnull().any()]

In [20]:
df[colunas_nulas].dtypes

TP_CATEGORIA_ESCOLA_PRIVADA    float64
TP_LOCALIZACAO_DIFERENCIADA    float64
NU_ENDERECO                     object
DS_COMPLEMENTO                  object
NO_BAIRRO                       object
                                ...
QT_TUR_INF_PRE_INT             float64
QT_TUR_FUND_INT                float64
QT_TUR_FUND_AI_INT             float64
QT_TUR_FUND_AF_INT             float64
QT_TUR_MED_INT                 float64
Length: 401, dtype: object

In [21]:
# 3. Filtrar apenas as que s√£o num√©ricas
colunas_nulas_numericas = [col for col in colunas_nulas if pd.api.types.is_numeric_dtype(df[col])]

In [27]:
df_itambe

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
3819,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0
3820,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,19.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0
3821,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,16.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3822,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3823,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3824,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3825,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3826,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,9.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0,0.0
3827,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,11.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3828,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3829,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3830,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3831,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,12.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3832,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3833,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,13.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3834,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3835,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,13.0,0.0,0.0,13.0,13.0,0.0,0.0,0.0,0.0,0.0
3836,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3837,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3838,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3839,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3840,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3841,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3842,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,11.0,0.0,0.0,11.0,11.0,0.0,0.0,0.0,0.0,0.0
3843,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,25.0,0.0,0.0,11.0,3.0,8.0,0.0,0.0,0.0,0.0
3844,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3845,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3846,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,22.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3847,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
escolas_com_biblioteca = df_itambe[df_itambe['IN_BIBLIOTECA'] == 1]

In [32]:
escolas_com_biblioteca

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
3819,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0
3820,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,19.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0
3821,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,16.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3831,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,12.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3834,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3836,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3837,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3840,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3845,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3846,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,22.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3847,2024,Nordeste,2,Pernambuco,PE,26,Itamb√©,2607653,Recife,2601,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
# Ver a propor√ß√£o das escolas em Itamb√©
# Isso mostra a porcentagem de escolas com (1) e sem (0) biblioteca.

df_itambe['IN_BIBLIOTECA'].value_counts(normalize=True) * 100

IN_BIBLIOTECA
0.0    62.068966
1.0    37.931034
Name: proportion, dtype: float64

In [38]:
df_itambe['TP_LOCALIZACAO'].value_counts()
# 1 - Urbana | 2 - Rural

TP_LOCALIZACAO
1    21
2     8
Name: count, dtype: int64